In [2]:
from detection_utils.universal_detection_api import UniversalObjectDetector

In [ ]:
%cd ..

In [3]:
with open("bricks/2357 brick corner 1x2x2/2357 brick corner 1x2x2 011L.jpg","rb")as file:
    data = file.read()

In [4]:
#detector = UniversalObjectDetector("yolov8n_lego_416_bsize_1")
detector = UniversalObjectDetector("ssd_resnet101_v1_fpn_640x640_coco17_tpu-8", "workspace/data/label_map.pbtxt")

In [5]:
detector.detect_objects(data)

{'time': {'preprocess': 3.6162000033073127,
  'inference': 7637.1681000018725,
  'postprocess': 6.9844999961787835},
 'boxes': [[73, 88, 285, 313, '3022 Plate 2x2', 0.6226392984390259],
  [67, 91, 283, 313, '3040 roof tile 1x2', 0.6075388789176941]]}

In [6]:
detector.raw_detection(data)

{'num_detections': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([        100], dtype=float32)>,
 'detection_anchor_indices': <tf.Tensor: shape=(1, 100), dtype=float32, numpy=
 array([[      50719,       50725,       50719,       50725,       50725,       50605,       50731,       50605,       50731,       51068,       50725,       50665,       50785,       50731,       50605,       50789,       49611,       49611,       50603,       49897,       50731,       50011,       50785,
               49657,       50665,       50131,       49771,       50731,       49611,       49537,       50137,       48265,       49730,       50785,       50125,       48971,       49783,       49611,       50731,       50605,       49543,       49211,       48266,       48277,       50023,       48841,
               49423,       49081,       48272,       48260,       50789,       50603,       44172,       49321,       43932,       45042,       48284,       48289,       44412,       43692,       45282,